name = "javascriptgpt"
main = "src/index.js"
compatibility_date = "2026-01-01"

compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

kv_namespaces = [
  { binding = "JavaScriptKV", id = "244f9786d69e40608cf4b894f255da0a" }
]

[[d1_databases]]
binding = "JavaScriptD1"
database_name = "javascriptgpt-db"
database_id = "dc751040-8565-4206-ae9d-2cd3b3898cd9"

[durable_objects]
bindings = [
  { name = "CHAT_SESSION", class_name = "ChatSessionDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatSessionDO"]
